apiVersion: apps/v1
kind: Service
metadata:
  name: cmdb-service
  labels:
      env: test
spec:
  type: NodePort
  selector:
    env: test
    app: cmdb
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: redis
    port: 8888
    targetPort: 6379
